version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
    links:
      - db:db

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty123$$%